const ESCAPE = 27;

const DEFAULT_SCALE = 100;

const MIN_SCALE = 25;
const MAX_SCALE = 100;
const MIN_SCALE_STEP = 0;
const MAX_SCALE_STEP = 25;

const MIN_HASHTAG_LENGTH = 2;
const MAX_HASHTAG_LENGTH = 20;
const MAX_HASHTAG_COUNT= 5;
const MAX_DESCRIPTION_LENGTH = 140;

const ERROR_DELAY = 5000;

const WORD_LENGTH = 6;
const SLIDER_DEFAULT_MIN = 0;
const SLIDER_DEFAULT_MAX = 100;
const SLIDER_DEFAULT_START = 100;
const SLIDER_DEFAULT_STEP = 1;

const RERENDER_DELAY = 500;
const NUMBER_NEEDLESS_PHOTOS = 15;

const COMMENTS_ARRAY_LENGTH_LIMITER = 5;
const ADD_COMMENTS_STEP = 5;

const FILE_TYPES = ['gif', 'jpg', 'jpeg', 'png'];

export {ESCAPE,
  DEFAULT_SCALE,
  MIN_SCALE,
  MAX_SCALE,
  MIN_SCALE_STEP,
  MAX_SCALE_STEP,
  MIN_HASHTAG_LENGTH,
  MAX_HASHTAG_LENGTH,
  MAX_HASHTAG_COUNT,
  MAX_DESCRIPTION_LENGTH,
  ERROR_DELAY,
  RERENDER_DELAY,
  NUMBER_NEEDLESS_PHOTOS,
  FILE_TYPES,
  COMMENTS_ARRAY_LENGTH_LIMITER,
  ADD_COMMENTS_STEP,
  WORD_LENGTH,
  SLIDER_DEFAULT_MIN,
  SLIDER_DEFAULT_MAX,
  SLIDER_DEFAULT_START,
  SLIDER_DEFAULT_STEP};
