const ESCAPE = 27;

const DEFAULT_SCALE = 100;

const MIN_SCALE = 25;
const MAX_SCALE = 100;
const MIN_SCALE_STEP = 0;
const MAX_SCALE_STEP = 25;

const MIN_HASHTAG_LENGTH = 2;
const MAX_HASHTAG_LENGTH = 20;
const MAX_HASHTAG_COUNT= 5;
const MAX_DESCRIPTION_LENGTH = 140;

const ERROR_DELAY = 5000;

const RERENDER_DELAY = 500;
const NUMBER_NEEDLESS_PHOTOS = 15;

export {ESCAPE, DEFAULT_SCALE, MIN_SCALE, MAX_SCALE, MIN_SCALE_STEP, MAX_SCALE_STEP,MIN_HASHTAG_LENGTH, MAX_HASHTAG_LENGTH, MAX_HASHTAG_COUNT, MAX_DESCRIPTION_LENGTH, ERROR_DELAY, RERENDER_DELAY, NUMBER_NEEDLESS_PHOTOS};
